# This is an example of ansible playbook written in YMAL

# YAML FILE STARTS WITH THREE --- DASHES(---)
---
- hosts: web
# host is to define the name of your host machine, group or all servers
# in this example we are targeting server called web

  gather_facts: yes
# gethering facts before performing any tasks

  become: true
# become is used to get root permission to perform any tasks that may require admin access

  tasks:
#Tasks are executed in order, one at a time, against all Servers matched by the host pattern
# Every task should have a name, which is included in the output from running the playbook
# The goal of each task is to execute a module, with very specific arguments.

  - name: Install nginx
  # we are installing nginx on our web server 
  
    apt: pkg=nginx state=present
    notify:
    - restart nginx
    - name: Enable nginx during boot
      service: name=nginx  state=started enabled=yes
  handlers:
          - name: restart nginx
            service: name=nginx state=restarted
